Moved repository from Travis to GitHub Actions
adafruit/Adafruit_CircuitPython_Colorsys pull request #6
Opened 2020-01-09 22:36 UTC by dherrada

2020-01-09 23:12 UTC, dherrada commented
Personally, I think the best course of action for this would be reverting the most recent commit

2020-01-09 23:21 UTC, siddacious commented
@dherrada This is failing for a documentation build issue and it was already failing, though it may have been hard to tell because what looks like a typo in the cookiecutter setup broke the link to Travis. It's here:
https://travis-ci.com/adafruit/Adafruit_CircuitPython_CPython

Can you give more detail about why you were suggesting reverting the most recent commit?

2020-01-09 23:23 UTC, dherrada commented
@siddacious Prior to the most recent commit, the only issues were pylint issues in the docstring of adafruit__cpython.py. In fixing the pylint issues, I messed up some of the rst which caused it to fail.

2020-01-09 23:23 UTC, siddacious requested changes

2020-01-09 23:23 UTC, siddacious commented on adafruit__cpython.py
> +.. todo:: Add links to any specific hardware product page(s), or category
Your attempts to get this passing are admirable but RST doesn't play fair. You can undo this.

2020-01-09 23:23 UTC, siddacious commented on adafruit__cpython.py
> +.. todo:: Uncomment or remove the Bus Device and/or the Register library
This can be reverted as well

2020-01-09 23:26 UTC, siddacious commented
@dherrada ah! I see what you mean. Ya, go ahead and revert the TODO changes

2020-01-09 23:27 UTC, dherrada commented
@siddacious Ok. Will rebase in 1 sec

2020-01-10 00:07 UTC, siddacious approved these changes

2020-01-10 00:07 UTC, merged